version: '3.7'
services:

  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: academia_alunos_db
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno
    ports:
      - 3306:3306

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "db:database"
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: on-failure

networks:
  alunos:
    driver: custom-driver-1